apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golf-handicap-data
  labels:
    app: golf-handicap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
