apiVersion: v1
kind: Service
metadata:
  name: golf-handicap-tracker
  labels:
    app: golf-handicap-tracker
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: golf-handicap-tracker
