apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../pvc.yaml
  - ../../backend-deployment.yaml
  - ../../backend-service.yaml
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../ingress.yaml

commonLabels:
  app: golf-handicap-tracker
  ingress: nginx
